apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
      - name: kube
        image: morgankaufmann/deep-render
